# Change these first
owner: targed # Your GitHub organization or username, where this repository lives
repo: uptest # The name of this repository

sites:
  - name: APIs.guru
    url: https://apis.guru/.well-known/ai-plugin.json
  - name: Appypie
    url: https://www.appypie.com/.well-known/ai-plugin.json
  - name: Asana
    url: https://app.asana.com/.well-known/ai-plugin.json
  - name: ASCIIArt
    url: https://chatgpt-plugin-ts.transitive-bullshit.workers.dev/.well-known/ai-plugin.json
  - name: Babyagichatgpt
    url: https://babyagichatgpt.skirano.repl.co/.well-known/ai-plugin.json
  - name: Biztoc
    url: https://biztoc.com/.well-known/ai-plugin.json
  - name: Brainlox
    url: https://brainlox.ai/.well-known/ai-plugin.json
  - name: Bundlejs
    url: https://deno.bundlejs.com/.well-known/ai-plugin.json
  - name: Calculator
    url: https://chat-calculator-plugin.supportmirage.repl.co/.well-known/ai-plugin.json

status-website:
  baseUrl: /uptest
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Plugins
  introTitle: "Plugins Uptime"
  introMessage: This status page monitors [Plugins](https://github.com/targed/GPT-Plugins) for uptime.
  navbar:
    - title: Status
      href: /uptest
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
