# Change these first
owner: targed # Your GitHub organization or username, where this repository lives
repo: uptest # The name of this repository

sites:
  - name: WolframAlpha
    url: https://www.wolframalpha.com/.well-known/ai-plugin.json
  - name: Wikipedia
    url: https://oasst-plugins.dumbserg.al:2083/plugins/wikipedia-plugin.json
  - name: Calculator
    url: https://chat-calculator-plugin.supportmirage.repl.co/.well-known/ai-plugin.json

status-website:
  baseUrl: /uptest
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Plugins
  introTitle: "Plugins Uptime"
  introMessage: This status page monitors [Plugins](https://github.com/targed/GPT-Plugins) for uptime.
  navbar:
    - title: Status
      href: /uptest
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
